# Generated by Django 4.2.5 on 2023-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='사용자 아이디', max_length=20)),
                ('name', models.CharField(help_text='사용자 이름', max_length=100)),
                ('email', models.EmailField(help_text='사용자 이메일', max_length=254)),
                ('password', models.CharField(help_text='사용자 비밀번호', max_length=20)),
            ],
        ),
    ]
