# Generated by Django 4.2.5 on 2023-09-11 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_product_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('reg_date_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('finish_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.recorddetail')),
            ],
        ),
    ]
