# Generated by Django 4.2.5 on 2023-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_record_recorddetail_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddetail',
            name='altitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recorddetail',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recorddetail',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recorddetail',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='GPS',
        ),
    ]
