# Generated by Django 4.2.5 on 2023-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_recorddetail_altitude_recorddetail_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recorddetail',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
