# Generated by Django 4.2.5 on 2023-09-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_product_id_alter_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddetail',
            name='altitude',
            field=models.FloatField(default=0, help_text='고도'),
        ),
        migrations.AlterField(
            model_name='recorddetail',
            name='latitude',
            field=models.FloatField(default=0, help_text='위도'),
        ),
        migrations.AlterField(
            model_name='recorddetail',
            name='longitude',
            field=models.FloatField(default=0, help_text='경도'),
        ),
        migrations.AlterField(
            model_name='recorddetail',
            name='record_id',
            field=models.ForeignKey(help_text='Record 객체의 id', on_delete=django.db.models.deletion.CASCADE, to='record.record'),
        ),
        migrations.AlterField(
            model_name='recorddetail',
            name='speed',
            field=models.FloatField(default=0, help_text='속도'),
        ),
    ]
