# Generated by Django 4.2.5 on 2023-09-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_alter_recorddetail_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='distance',
            field=models.FloatField(default=0, help_text='이동 거리'),
        ),
        migrations.AddField(
            model_name='record',
            name='record',
            field=models.TimeField(help_text='기록 시간', null=True),
        ),
    ]
